// <auto-generated />
using System;
using BLL.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BLL.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20241203135614_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BLL.DAL.Oblasts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeputyNumber")
                        .HasColumnType("int");

                    b.Property<string>("OblastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Oblasts");
                });

            modelBuilder.Entity("BLL.DAL.PartiesParticipationOblast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OblastId")
                        .HasColumnType("int");

                    b.Property<int?>("OblastsId")
                        .HasColumnType("int");

                    b.Property<int?>("PartyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PoliticalPartiesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OblastsId");

                    b.HasIndex("PoliticalPartiesId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("BLL.DAL.PoliticalParties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LastPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PoliticalParties");
                });

            modelBuilder.Entity("BLL.DAL.Rayons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OblastId")
                        .HasColumnType("int");

                    b.Property<int?>("OblastsId")
                        .HasColumnType("int");

                    b.Property<int>("VoterNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OblastsId");

                    b.ToTable("Rayons");
                });

            modelBuilder.Entity("BLL.DAL.PartiesParticipationOblast", b =>
                {
                    b.HasOne("BLL.DAL.Oblasts", "Oblasts")
                        .WithMany("Parties")
                        .HasForeignKey("OblastsId");

                    b.HasOne("BLL.DAL.PoliticalParties", "PoliticalParties")
                        .WithMany("OblastParticipation")
                        .HasForeignKey("PoliticalPartiesId");

                    b.Navigation("Oblasts");

                    b.Navigation("PoliticalParties");
                });

            modelBuilder.Entity("BLL.DAL.Rayons", b =>
                {
                    b.HasOne("BLL.DAL.Oblasts", "Oblasts")
                        .WithMany("Rayons")
                        .HasForeignKey("OblastsId");

                    b.Navigation("Oblasts");
                });

            modelBuilder.Entity("BLL.DAL.Oblasts", b =>
                {
                    b.Navigation("Parties");

                    b.Navigation("Rayons");
                });

            modelBuilder.Entity("BLL.DAL.PoliticalParties", b =>
                {
                    b.Navigation("OblastParticipation");
                });
#pragma warning restore 612, 618
        }
    }
}
